// vue-counter/src/components/counter.vue
<template>
    <div style="text-align:center; position:relative">
        <h1>계산기</h1>
        <div style="display: flex; align-items: center; justify-content: center; gap: 10px;">
        <button @mousedown="startDecrement" @mouseup="stop">-</button>
        <h2> {{ counter }}</h2>
        <button @mousedown="startIncrement" @mouseup="stop">+</button>
        </div>
        <button @click="reset" style="position:absolute;margin-top:30px;right:30%;">Reset</button>
    </div>
</template>

<script>
    export default {
        name:'CounterComponent',
        data(){
            return {
                counter:0, intervalID: null,
                };
            },
        methods:{
            increment(){
                this.counter++;
            },
            decrement(){
                this.counter--;
            },
            startIncrement(){
                this.intervalID=setInterval(() => this.increment(), 40);
            },
            startDecrement(){
                this.intervalID=setInterval(() => this.decrement(), 40);
            },
            stop(){
                clearInterval(this.intervalID);
            },
            reset(){
                this.counter=0;
            }
        },

    };
</script>

// react-counter/src/components/counter.jsx
import React,{useState} from "react";

const Counter=()=>{
    const [counter, setCounter]=useState(0);
    const [intervalID, setIntervalID]=useState(null);

    const increment=()=>{
        const ID=setInterval(()=>setCounter(counter=>counter+1),40);
        setIntervalID(ID);
    };
        
    const decrement=()=>{
        if (counter>0){
            const ID=setInterval(()=>setCounter(counter=>counter-1),40);
            setIntervalID(ID);
        };
    };

    const stop=()=>{
        clearInterval(intervalID);
        setIntervalID(null);
    };
    const reset=()=>setCounter(0);

    return (
        <div style={{textAlign:'center',position:'realative'}}>
            <h1>카운터</h1>
            <div style={{display: 'flex', alignItems:'center', justifyContent:'center', gap:'10px'}}>
                <button onMouseDown={decrement} onMouseUp={stop}>-</button>
                <h2>{counter}</h2>
                <button onMouseDown={increment} onMouseUp={stop}>+</button> 
            </div>
            <button onClick={reset} style={{position:'absolute',marginTop:'30px',right:'30%'}}>리셋</button>      
        </div>
    );
};

export default Counter;
