// vue-counter/src/components/counter.vue
<template>
    <div style="text-align:center; position:relative">
        <h1>계산기</h1>
        <div style="display: flex; align-items: center; justify-content: center; gap: 10px;">
        <button @mousedown="startDecrement" @mouseup="stop">-</button>
        <h2> {{ counter }}</h2>
        <button @mousedown="startIncrement" @mouseup="stop">+</button>
        </div>
        <button @click="reset" style="position:absolute;margin-top:30px;right:30%;">Reset</button>
    </div>
</template>

<script>
    export default {
        name:'CounterComponent',
        data(){
            return {
                counter:0, intervalID: null,
                };
            },
        methods:{
            increment(){
                this.counter++;
            },
            decrement(){
                this.counter--;
            },
            startIncrement(){
                this.intervalID=setInterval(() => this.increment(), 40);
            },
            startDecrement(){
                this.intervalID=setInterval(() => this.decrement(), 40);
            },
            stop(){
                clearInterval(this.intervalID);
            },
            reset(){
                this.counter=0;
            }
        },

    };
</script>

// Angular-counter/src/app/counter/counter.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-counter',
  imports: [],
  templateUrl: './counter.component.html',
  styleUrl: './counter.component.css'
})
export class CounterComponent {
  counter=0;
  intervalID: any=null;

  increment() {
    this.counter++
  }

  decrement() {
    if(this.counter>0){
    this.counter--
    }
  } 

  startinc(){
    this.intervalID=setInterval(()=>{
      this.increment();
    },100);
  }

  stop(){
    clearInterval(this.intervalID);
  }

  startdec(){
    this.intervalID=setInterval(()=>{
      this.decrement();
    },100);
  }

}

<div style="text-align: center; position: relative;">
    <h1>계산기</h1>
    <div style="display: flex; align-items: center; justify-content: center; gap: 10px;">
        <button (mousedown)="startdec()" (mouseup)="stop()">-</button>
        <h2>{{ counter }}</h2>
        <button (mousedown)="startinc()" (mouseup)="stop()">+</button>
    </div>
    <button (click)="reset()" style="position: absolute; bottom: 10px; right: 10px;">Reset</button>
</div>
